[package]
name = "php-pagefind"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "*"
pagefind = "*"
futures = "0.3"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "fs"] }

[profile.release]
strip = "debuginfo"
