name: ci.yml
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find extension directory
        run: php -i | grep "extension_dir => /"
      - name: Build
        run: cargo build --verbose
